### ISSUE TITLE
Cannot pass lending iterator and iterate

### ISSUE THREAD

**Issue by vigna** [Crazytieguy/gat-lending-iterator#12]
We are using your lending iterator in our reimplementation of WebGraph in Rust (https://github.com/vigna/webgraph-rs). We have a problem passing a lending iterator and iterate:
```rust
use gat_lending_iterator::LendingIterator;

fn test_iter<'a, I: Iterator<Item = usize>>(
    mut iter: impl LendingIterator<Item<'a> = (usize, I)> + 'a,
) {
    while let Some((_x, _y)) = iter.next() {}
}
```

This gives
```
cannot borrow `iter` as mutable more than once at a time
`iter` was mutably borrowed here in the previous iteration of the loop
```

Is there anything we're doing wrong?

**Comment by Crazytieguy** [comment]
Hi! thanks for opening an issue.

The issue here is that `Item` should be `(usize, I)` for *any* lifetime, not a specific lifetime `'a` that's constant throughout the function invocation.

Try this instead:

```
fn test_iter<I: Iterator<Item = usize>>(
    mut iter: impl for <'a> LendingIterator<Item<'a> = (usize, I)>,
) {
    while let Some((_x, _y)) = iter.next() {}
}
```

**Comment by Crazytieguy** [comment]
Actually, in that case you might not need a `LendingIterator` in the first place. Is the lifetime of I tied to the lifetime of the lending iterator? because that would look a bit different

**Comment by vigna** [comment]
And, I was able to make this into a [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e2d97fda42c92f9509691e6da2c636be) !

**Comment by Crazytieguy** [comment]
Ok so if I understand correctly, it's kind of like [itertools::group_by](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.group_by), but guaranteed to never allocate. I will give it a try

**Comment by Crazytieguy** [comment]
Here is what I came up with. It has a limitation that the small iterators are a concrete type rather than a generic, I'm not sure how to get around this without the nightly `type_alias_impl_trait` feature. Does this help?

```rust
struct GroupByFirst<I: Iterator<Item = (usize, usize)>> {
    iter: std::iter::Peekable<I>,
}

impl<I: Iterator<Item = (usize, usize)>> GroupByFirst<I> {
    fn new(iter: I) -> Self {
        Self {
            iter: iter.peekable(),
        }
    }
}

struct Group<'a, I: Iterator<Item = (usize, usize)>> {
    iter: &'a mut std::iter::Peekable<I>,
    first: usize,
}

impl<'a, I: Iterator<Item = (usize, usize)>> Iterator for Group<'a, I> {
    type Item = usize;

    fn next(&mut self) -> Option<Self::Item> {
        self.iter
            .next_if(|&(first, _)| first == self.first)
            .map(|(_, second)| second)
    }
}

impl<I: Iterator<Item = (usize, usize)>> LendingIterator for GroupByFirst<I> {
    type Item<'a> = (usize, Group<'a, I>) where I: 'a;

    fn next(&mut self) -> Option<Self::Item<'_>> {
        let &(first, _) = self.iter.peek()?;
        Some((
            first,
            Group {
                iter: &mut self.iter,
                first,
            },
        ))
    }
}

fn print_groupby_items<I, G>(mut groupby: G)
where
    I: Iterator<Item = (usize, usize)>,
    G: for<'a> LendingIterator<Item<'a> = (usize, Group<'a, I>)>,
{
    while let Some((first, group)) = groupby.next() {
        println!("{first}");
        for second in group {
            println!("{second}");
        }
    }
}

#[test]
fn group_by() {
    let iter = [0, 0, 1, 1, 2, 2].into_iter().zip(0..6);
    let mut groupby = GroupByFirst::new(iter);
    if let Some((first, mut group)) = groupby.next() {
        assert_eq!(first, 0);
        assert_eq!(group.next(), Some(0));
        assert_eq!(group.next(), Some(1));
    }
    if let Some((first, mut group)) = groupby.next() {
        assert_eq!(first, 1);
        assert_eq!(group.next(), Some(2));
        assert_eq!(group.next(), Some(3));
    }
    print_groupby_items(groupby);
}
```

**Comment by vigna** [comment]
That sounds like the solution for our main problem, and I'm going to look into it. BTW, we were thinking of doing some PR to the library because we're using it and we need a few more things. We could port some code from `lending-iterator` if you're ok with that, as I guess it should be pretty easy.

What we still cannot solve is the problem in the playground above—how do you pass around a lending iterator like that? If you have an answer also to that, we would be (again) immensely grateful.

**Comment by Crazytieguy** [comment]
Ok I simplified it a bit so it's easier to play with it and I think I got it [working](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5fd8696678c0c9f838fb23d3b4980a0c)

Let me know if you have trouble adding the tuples back in. Also - I still think you might just want to use a concrete type for the inner iterator (see my previous example, in particular `print_groupby_items`).

Regarding contributing - sure! you're more than welcome. Ideally create an issue for a few methods you would like to implement so I can make sure we're not working on the same methods. Or maybe I'll commit my work in progress first, probably tomorrow

**Comment by Crazytieguy** [comment]
I think the changes I made to how the trait bounds are specified should fix the issue even with the tuple version. I'll try it later today but might not have time until tomorrow

**Comment by Crazytieguy** [comment]
[Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=01ef4d2201c2bedd087fd26257c9d7bf)

Let me know if I missed something

**Comment by vigna** [comment]
Oh wow. This journey is full of surprises. 

I have to test this. Syntax is perfect, but I don't understand how an implementation would work because the iterator has no lifetime, and definitely the iterator has a lifetime, as it depends on the graph.

**Comment by vigna** [comment]
I guess [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e98a218c337ab35cf663c8e162d6c972) should be it but I have to try an implementation.

**Comment by vigna** [comment]
So, I tried to [implement](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4d61ca5485159b42acfb3ae7e56eeedc) the trait, reusing a sample implementation from David, but no joy: I did it in the "obvious" way and the compiler complains cryptically. I'm going to look further into it but maybe you have suggestions.

Note that `iter_nodes()` must not consume `self`.

**Comment by Crazytieguy** [comment]
I tried to solve it by [simplifying](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=978ff2a8d7a88d5a99ee67dbe56e3b6f) again, and I hit a clear wall - a bound such as `for<'a> L::Item<'a>: Trait` is not limited to `L: 'a`, but in the trait `Item` *is* limited to `Self: 'a`. I don't know if there's a way around this other than - again - just using concrete types or inherent methods instead of insisting that functions such as `scan` are generic (see my first example above).

If you find a way around this please let me know, I would definitely be interested

**Comment by Crazytieguy** [comment]
Oh and I do think that if you're able to solve my simplified case it can generalize to the complicated case. The tuples and SimplifiedGraph trait are already solved IMO.

**Comment by vigna** [comment]
What we're using now (and it's basically working, we just need some `'static` fairy dust when global state is involved) can be found [here](https://github.com/vigna/webgraph-rs/blob/havoc/src/traits/iter.rs). It is basically the last suggestion by Daniel, and indeed it resembles the way he implements "fake GATs" in his library.

I've read elsewhere, too, and I'm convinced now, that simply having an item with a lifetime is not sufficient for a flexible lending iterator. I don't fully understand the implication of Daniel's design, but the `for` in the definition and the automatic propagation of `Self: 'b` seem to be essential.

**Comment by Crazytieguy** [comment]
What do you mean by automatic propagation of `Self: 'b`? Can you link the relevant piece of code? Sounds interesting

**Comment by vigna** [comment]
https://github.com/vigna/webgraph-rs/blob/bf7f83d6e8d7f53392cf35b783842b2917d62bde/src/traits/iter.rs#L46

**Comment by vigna** [comment]
Question: do you think this trait for a lending iterator would be a better base for a library than the simpler trait in which simply items have a borrowed lifetime? We are slowly developing thinks like take, for_each, etc., for the lending iterator above, and certainly we will make this stuff into a library, but maybe you might consider using this trait instead of the simple one for gat_lending_iterator, and we could contribute to your library instead. Just to avoid to write the same code twice... our experience is that this definition makes it possible to do things like wrapping iterators or having iterators depending on global state whose returned items depend on the same global state.

**Comment by Crazytieguy** [comment]
Hey sorry for the slow reply, did you end up turning it into a library? This seems interesting and I'm going to play around with it a bit today

**Comment by vigna** [comment]
We ended up being maintainers of [Lender](https://crates.io/crates/lender), which does exactly what we were trying to do with [our library](https://crates.io/crates/hrtb-lending-iterator). You are welcome to join if you're interested—the author basically told me he's done with it and entirely happy if someone else picks it up.

**Comment by Crazytieguy** [comment]
Ok cool! I will do some experiments today and keep you updated, but I'll probably end up mostly maintaining this gat version, even if it's just for diversity's sake

**Comment by vigna** [comment]
If you're interested, [this blog entry](https://sabrinajewson.org/blog/the-better-alternative-to-lifetime-gats) explains why lifetime GATs are basically useless for the purpose of lending iterators—only very elementary cases can be covered.

**Comment by Crazytieguy** [comment]
Ok I've read the blog post now and it's pretty interesting. So I guess webgraph uses workaround 3 right? Is Lender using one of these workarounds?

Anyway I think it's nice to have the gat version for people that have the simple use cases it allows, and it would become more useful in the future if we get lifetime bounds in HRTBs

**Comment by vigna** [comment]
Yes, Lender and our abandoned crate are based on the third workaround.

The GAT version is infinitely easier to handle, in particular when you want to have bounds on the returned item.
