### ISSUE TITLE
Publish this on crates.io

### ISSUE THREAD

**Issue by CraigPersonal100** [Crazytieguy/gat-lending-iterator#2]
I have seen that one possible path forward is to merge this crate with https://github.com/danielhenrymantilla/lending-iterator.rs ( https://github.com/danielhenrymantilla/lending-iterator.rs/issues/10#issuecomment-1383026263).

However, as per that discussion, I think this crate has merit itself to be published as a standalone crate, at least until lending iterators arrive in the standard library or Daniel's version adds a GAT module.

To avoid conflict with the name, maybe publish this on crates.io as gat-lending-iterator.

**Comment by Crazytieguy** [comment]
I'm glad there's demand! I'll publish it

**Comment by Crazytieguy** [comment]
Done :) I'm going to open some issues for making the crate a bit more ready for actual use

**Comment by Crazytieguy** [comment]
Although it seems that since I've made this repo two other implementations appeared on crates.io... then again I'm going to have some time to maintain this in the near future so It's probably not all bad
